# Generated by Django 5.0.6 on 2024-06-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSF_app', '0002_remove_refereelicense_nr_missions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='website',
            new_name='district_website',
        ),
        migrations.AddField(
            model_name='district',
            name='district_email',
            field=models.EmailField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='district',
            name='district_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
