# Generated by Django 5.0.6 on 2024-06-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSF_app', '0003_rename_website_district_district_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='social_security_nr',
            field=models.CharField(help_text='YYMMDD-XXXX', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='refereelicense',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('non-active', 'Non-active'), ('pending', 'Pending')], default='pending', max_length=255),
        ),
    ]
