# Generated by Django 5.0.6 on 2024-06-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSF_app', '0004_alter_person_social_security_nr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='age_categories',
            field=models.ManyToManyField(to='SSF_app.agecategory'),
        ),
        migrations.AlterField(
            model_name='refereelicense',
            name='referee_category',
            field=models.CharField(choices=[('distriksdomare', 'Distriksdomare'), ('förbundsdomare', 'Förbundsdomare'), ('internationell domare kat 1', 'Internationell domare kat 1'), ('internationell domare kat 2', 'Internationell domare kat 2')], default='Ej angivet', max_length=255),
        ),
    ]
