# Generated by Django 5.0.6 on 2024-06-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSF_app', '0004_alter_person_social_security_nr_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lifterlicense',
            name='unique_license',
        ),
        migrations.AddField(
            model_name='lifterlicense',
            name='requested_year',
            field=models.IntegerField(default=2024, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6),
        ),
        migrations.AlterField(
            model_name='refereelicense',
            name='referee_category',
            field=models.CharField(choices=[('distriksdomare', 'Distriksdomare'), ('förbundsdomare', 'Förbundsdomare'), ('internationell domare kat 1', 'Internationell domare kat 1'), ('internationell domare kat 2', 'Internationell domare kat 2')], default='Ej angivet', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='lifterlicense',
            constraint=models.UniqueConstraint(fields=('person', 'license_nr', 'requested_year'), name='unique_license'),
        ),
    ]
