# Generated by Django 5.0.6 on 2024-06-23 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SSF_app', '0005_series_age_categories_and_more'),
        ('SSF_app', '0006_remove_refereelicense_unique_referee_license_and_more'),
    ]

    operations = [
    ]
